[default]

optimizer = true
optimizer_runs = 1000000

src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
verbosity = 3
#solc_version = '0.8.10'

# See more config options https://github.com/gakonst/foundry/tree/master/config